### PR TITLE
Add `node_modules` to .gitignore & remove `node_modules` from repo

### PR DESCRIPTION
**Pull request by keesvv**
Hoi @QkeleQ10! :smile: 

Just stumbled across this project and wanted to help out a little. This pull request removes `node_modules` from the repository and adds a `.gitignore` file that prevents `node_modules` being committed in the future.

The reason being is that it's never a good idea to commit your project's dependencies: they are very large in size, Git and GitHub do not like large directories, and most of the time they are optimized for your own computer and environment.

The `package-lock.json` file is responsible for keeping the versions of all installed packages and dependencies: when someone clones your repo, they just have to run `npm install` and they're set.

Just my two cents!

### CODE REVIEW

**Comment by QkeleQ10** [comment]
Oh alright I see, thanks for your contribution @keesvv ! In case you ever want to see the bot in action, just let me know. I could send you an invite to the server.

Also yes I'm a noob lol

**Comment by QkeleQ10** [comment]
I don't think it really works as I'm hosting on Heroku, or did I mess up?

**Comment by keesvv** [comment]
You're welcome!

Heroku is an awesome service, it provides lots of automation tools and it can install your dependencies automatically. How is your deployment pipeline set up? Are you pushing to an upstream branch from Heroku?

I believe they automatically install all packages for you when you deploy, but I don't use Heroku myself, so I don't really know to be honest.

**Comment by keesvv** [comment]
[This](https://devcenter.heroku.com/articles/getting-started-with-nodejs?singlepage=true) is something I've found.

Also, they state the following:
> Heroku recognizes an app as Node.js by the existence of a package.json file in the root directory. For your own apps, you can create one by running npm init --yes.

**Comment by QkeleQ10** [comment]
I've linked my Heroku App to automatically deploy from GitHub. This is the error I'm getting, if that helps: 
image

**Comment by QkeleQ10** [comment]
Yeah it did detect it as a node.js app, but it doesn't install the packages correctly...

**Comment by keesvv** [comment]
Ah, I see. In your `package.json`, some package versions are not synced up with the package versions defined in `package-lock.json`.

You can fix this by running `npm install` in the root of the repository on your own computer, and committing the changes made in `package-lock.json`.

**Comment by QkeleQ10** [comment]
oww right I'll try that thanks!

**Comment by QkeleQ10** [comment]
Alright that did it haha, tysm!

NB. Zal ik een linkje sturen naar de Discord server waar deze bot in zit? Het is best een coole server en de bot is ook in het Nederlands :P

**Comment by keesvv** [comment]
Nice, great to hear it worked!!

NB: Ja, leuk! Ben benieuwd :D

**Comment by QkeleQ10** [comment]
Alsjeblieft 😄 https://discord.gg/rcT948A

**Comment by keesvv** [comment]
Super, dankje! Zal ik doen :+1:

**Pull request merged**
